- name: Install Haproxy
  package:
    name: "{{item}}"
    state: latest
  with_items:
    - haproxy

- shell: "{{item}}"
  with_items:
    - echo "192.168.201.11    app1.loadbalancer.me     app1" >> /etc/hosts
    - echo "192.168.201.12   app2.loadbalancer.me     app2" >> /etc/hosts
    - mv /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.orig
    - echo "$ModLoad imudp" >> /etc/rsyslog.conf
    - echo "$UDPServerRun 514" >> /etc/rsyslog.conf
    - echo "local2.=info     /var/log/haproxy-access.log" >> /etc/rsyslog.d/haproxy.conf
    - echo "local2.notice    /var/log/haproxy-info.log" >> /etc/rsyslog.d/haproxy.conf

- name: Copy loadbalancer config
  copy:
    src: roles/haproxy/haproxy.cfg
    dest: /etc/haproxy/
    mode: 755

- shell: "{{item}}"
  with_items:
  - systemctl restart rsyslog
  - systemctl start haproxy
  - systemctl enable haproxy
