- name: Enable mongodb repo
  copy:
    src: roles/mongodb/mongodb-org.repo
    dest: /etc/yum.repos.d/
    mode: 755

- name: Install mongodb
  package:
    name: mongodb-org
    state: present

- name: Configure mongodb
  copy:
    src: roles/mongodb/mongod.conf
    dest: /etc/mongod.conf

- name: Restart mongodb
  service:
    name: mongod
    state: restarted
