---
- hosts: apps
  become: yes
  roles:
    - data-engineering-app

- hosts: mongodb
  become: yes
  roles:
    - mongodb

- hosts: elasticsearch
  become: yes
  roles:
    - elasticsearch

#ansible-playbook --inventory-file inventories/app deploy-app.yml
