---
- hosts: apps
  become: yes
  roles:
    - data-engineering-app
  environment:
    MONGODB_URI: "mongodb://mongo:27017"
    ELASTICSEARCH_URL: "http://elastic:9200"

# - hosts: haproxy
#   become: yes
#   roles:
#     - haproxy
#
# - hosts: mongodb
#   become: yes
#   roles:
#     - mongodb
#
# - hosts: elasticsearch
#   become: yes
#   roles:
#     - elasticsearch

#ansible-playbook --inventory-file inventories/app deploy-app.yml
