- name: Install Java and elasticsearch
  package:
    name: "{{item}}"
    state: latest
  with_items:
    - java-1.8.0-openjdk.x86_64
    - https://download.elastic.co/elasticsearch/elasticsearch/elasticsearch-1.7.3.noarch.rpm

- name: Start the elasticsearch service
  service:
    name: elasticsearch
    state: started

- shell: "{{item}}"
  with_items:
  - echo "192.168.201.11 app1" >> /etc/hosts
  - echo "192.168.201.12 app2" >> /etc/hosts
