
- name: Install packages
  package:
    name: "{{item}}"
    state: latest
  with_items:
      - git
      - epel-release
      - npm
      - python36
      - python-pip
      - python36-pip
      - python-devel
      - python36-devel
      - libffi-devel
      - gcc
      #- python-setuptools

#npm install pm2 -g
- name: Install pm2 to start app in background
  npm:
    name: pm2
    #args: -g
    global: yes
    state: present

- name: Make python3.6 default
  file:
    src: /usr/bin/python3.6
    dest: /usr/bin/python3
    state: link


- name: Copying project's files
  copy:
    src: roles/data-engineering-app/data-engineering
    dest: /home/vagrant/
    mode: 755

# ------------ TEST ------------
- name: Copying HELLO WORLD
  copy:
    src: roles/data-engineering-app/hello.py
    dest: /home/vagrant/
    mode: 755
# ------------------------------

- shell: which pip3.6
  register: pip36_exists
  ignore_errors: yes

- name: Update pip
  pip:
    executable: /usr/bin/pip3.6
    name: pip
    state: latest
  become: yes
  when: pip36_exists.stdout.find('pip3.6') != -1


- name: Install python requirements
  pip:
    executable: /usr/local/bin/pip3
    requirements: /home/vagrant/data-engineering/requirements.txt
  become: yes

- shell: "{{item}}"
  with_items:
    - echo "192.168.201.10 loadbalancer" > /etc/hosts
    # ------------ TEST ------------
    - pm2 start hello.py --interpreter=python3
    - pm2 start hello.py --interpreter=python3
    # ------------------------------
  ignore_errors: yes
