
- name: Install packages
  package:
    name: "{{item}}"
    state: latest
  with_items:
      - git
      - epel-release
      - python36
      - python-pip
      - python36-pip
      - python-devel
      - python36-devel
      - libffi-devel
      - gcc
      - python-setuptools

- name: Make python3.6 default
  file:
    src: /usr/bin/python3.6
    dest: /usr/bin/python3
    state: link

- name: Copying project's files
  copy:
    src: roles/data-engineering-app/data-engineering
    dest: /home/vagrant/
    mode: 755



# #------- Test pour effectuer ou non la tâche suivante -------
# - shell: which pip3.6
#   register: pip36_exists
#
# #- path: /usr/bin/pip3
# #  register: test_pip3
#
# #------- Doit être excuté qu'une fois -------
# - name: Update pip
#   pip:
#     executable: /usr/bin/pip3.6
#     name: pip
#     state: latest
#   become: yes
#   #when: test_pip3 is defined
#   #    OU
#   #when: test_pip3.stat.exists == False
#   when: pip36_exists.stdout.find('pip3.6') != -1
# # --------------------------

- name: Install python requirements
  pip:
    executable: /usr/local/bin/pip3
    requirements: /home/vagrant/data-engineering/requirements.txt
  become: yes
